version: '3.8'

services:
  # :::::::::::::::::::: DATABSE - PROVIDER:POSTGRES ::::::::::::::::::::::: #
  db:
    image: ${DOCKER__SERVICE_DB_IMAGE}
    container_name: ${DOCKER__SERVICE_DB_OPTION_CONTAINER_NAME}
    restart: ${DOCKER__SERVICE_DB_OPTION_RESTART}
    ports:
      - ${APP_DB__PORT_LOCAL}:${APP_DB__PORT_REMOTE}
    environment:
      - POSTGRES_DB=${APP_DB__NAME_DEFAULT}
      - POSTGRES_PASSWORD=${APP_DB__USER_DEFAULT_PASSWORD}
      - PGDATA=${APP_DB__VOLUME_DATA_REMOTE_PATH}
    volumes:
      - ${APP_DB__CONFIG_LOCAL}:${APP_DB__CONFIG_REMOTE}
      - ${APP_DB__SCRIPTS_LOCAL}:${APP_DB__SCRIPTS_REMOTE}
      - ${APP_DB__VOLUME_DATA_NAME}:${APP_DB__DATA_REMOTE_DEFAULT}

  # :::::::::::::::::::: DB ADMIN - PROVIDER = PGADMIN  ::::::::::::::::::::::: #
  db_admin:
    image: dpage/pgadmin4
    container_name: db_admin
    restart: ${DOCKER__SERVICE_DB_OPTION_RESTART}
    environment:
      - PGADMIN_DEFAULT_EMAIL=justin@rascode.dev
      - PGADMIN_DEFAULT_PASSWORD=code
    ports:
      - 5050:80
    volumes:
      - db_admin:${APP_DB_ADMIN__DATA_REMOTE}
  # :::::::::::::::::::: DOCKER NETWORKS (optional)  ::::::::::::::::::::::: #
  
  # your network settings here

  # :::::::::::::::::::: DOCKER VOLUMES  ::::::::::::::::::::::: #

volumes:
  postgres_db:
    name: ${DOCKER__SERVICE_DB_VOLUME_NAME}
    driver: ${DOCKER__VOLUME_DRIVER}
    driver_opts:
      mountpoint: ${APP_DB__DATA_LOCAL_DEFAULT}

  db_admin:
    driver: ${DOCKER__VOLUME_DRIVER}
    driver_opts:
      mountpoint: ${APP_DB_ADMIN__DATA_LOCAL}