version: '3.8'

services:
  # :::::::::::::::::::: DATABSE - PROVIDER:POSTGRES ::::::::::::::::::::::: #
  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    ports:
      - ${DB__PORT_LOCAL}:${DB__PORT_REMOTE}
    environment:
      - POSTGRES_DB=${DB__NAME_DEFAULT}
      - POSTGRES_PASSWORD=${DB__USER_DEFAULT}
      - PGDATA=${DB__DATA_REMOTE_MAPPED}
    volumes:
      - postgres_db:${DB__DATA_REMOTE_DEFAULT}
      - ./db/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh 
      - ./db/config:/var/lib/postgresql/data/pgdata
volumes:
  postgres_db:
    name: db
    driver: ${DOCKER__VOLUME_DRIVER}
    driver_opts:
      mountpoint: ${DB__DATA_LOCAL_DEFAULT}